version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb://mongodb:27017/product-orders
    volumes:
      - .:/app
    command: npm run start:dev
volumes:
  mongodb_data:
    driver: local
